### ISSUE TITLE
Android 8 app crash.

### ISSUE THREAD

**Issue by eugenenoble** [SergeyVinyar/AndroidAudioExample#4]
Steps:
1. btn Play in app.
2. btn Pause in notification.
3. close notification and open app
4. wait 5 sec.

**Comment by vladkalyuzhny** [comment]
```
02-15 15:08:24.225 21940-21940/ru.vinyarsky.androidaudioexample E/ActivityThread: Activity ru.vinyarsky.androidaudioexample.ui.MainActivity has leaked ServiceConnection ru.vinyarsky.androidaudioexample.ui.MainActivity$1@1f8673c that was originally bound here
                                                                                  android.app.ServiceConnectionLeaked: Activity ru.vinyarsky.androidaudioexample.ui.MainActivity has leaked ServiceConnection ru.vinyarsky.androidaudioexample.ui.MainActivity$1@1f8673c that was originally bound here
                                                                                      at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1336)
                                                                                      at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1231)
                                                                                      at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1450)
                                                                                      at android.app.ContextImpl.bindService(ContextImpl.java:1422)
                                                                                      at android.content.ContextWrapper.bindService(ContextWrapper.java:636)
                                                                                      at ru.vinyarsky.androidaudioexample.ui.MainActivity.onCreate(MainActivity.java:34)
                                                                                      at android.app.Activity.performCreate(Activity.java:6679)
                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
